### ISSUE TITLE
failed to run custom build command for `v4l2-sys-mit v0.2.0`

### ISSUE THREAD

**Issue by zxcqirara** [l1npengtul/nokhwa#174] opened 2024-06-03 15:58 UTC
Just created a new project, added this lib and tried to compile it. It throws this error:
```
error: failed to run custom build command for `v4l2-sys-mit v0.2.0`

Caused by:
  process didn't exit successfully: `/home/user/proj/target/debug/build/v4l2-sys-mit-844fdf7983ccc2a0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.56.0/src/ir/context.rs:846:9:
  "v4l2_pix_format_union_(anonymous_at_/usr/sbin/__/lib64/gcc/aarch64-linux-gnu/14_1_0/__/__/__/__/aarch64-linux-gnu/include/linux/videodev2_h_500_2)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm on x64 linux (WSL) and trying to compile it for aarch64 linux
My `Cargo.toml`:
```toml
[package]
name = "proj"
version = "0.1.0"
edition = "2021"

[dependencies]
nokhwa = { version = "0.10.4", features = ["input-native", "output-threaded"] }
```

**Comment by zxcqirara** [comment] 2024-06-03 16:26
Tried to cross build but it still throws an error:
```
error: failed to run custom build command for `mozjpeg-sys v1.1.1`

Caused by:
  process didn't exit successfully: `/target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build` (exit status: 1)
  --- stderr
  /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build)
  /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build)
  /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/debug/build/mozjpeg-sys-ef7e4aece9a75277/build-script-build)
warning: build failed, waiting for other jobs to finish...
```

**Comment by unwx** [comment] 2024-07-03 20:10
I encountered the same build failure. The root cause explained here: https://stackoverflow.com/a/76443281

I'm new to Rust, but it looks like:

- The v4l crate updated its bindgen dependency from 0.59 to 0.65 to solve that problem: https://github.com/raymanfx/libv4l-rs/commit/cf6d4125d3f37f24d18c325fd369f503d9f12a88
- nokhwa updated its v4l dependency on June 4th, 2023: https://github.com/l1npengtul/nokhwa/commit/f1405412e5e45f04339670d2f04aa88ccadb486b
- However, the latest nokhwa package on [crates.io](https://crates.io/crates/nokhwa) was updated on May 14th, 2023, and doesn't include this fix.

---

**Workaround**:

Building nokhwa from source (the [0.10](https://github.com/l1npengtul/nokhwa/tree/0.10) branch) resolved the issue for me.

**Additional Notes**:

On Fedora, I needed to install the following development packages for the build to succeed: 

`fontconfig-devel, alsa-lib-devel, libudev-devel`

**Comment by l1npengtul** [comment] 2024-10-12 14:39
0.10.5 has updated the libv4l-rs dependency. Should be fixed, please feel free to open a new issue if issue persists

**Closed as completed by l1npengtul** 2024-10-12 14:39 UTC
